### ISSUE TITLE
无法访问 http://ip:1778

### ISSUE THREAD

**Issue by wenbobao** [546669204/RebateBot#1]
亲，你好，我按照文档配置好了环境，但是无法访问 http://ip:1778这个地址. 如下图所示

![](http://owik45kut.bkt.clouddn.com/WX20180821-224425.png)

请问这是什么原因哈，谢谢

**Comment by 546669204** [comment]
数据库没有配置或者缺少版本初始化文件msgprocess目录下需要有sql目录并且有sql文件

**Comment by wenbobao** [comment]
谢谢大佬， 现在服务已经启动起来了，不过android 的 wehook一直闪退，报了下面的错误，

![](http://owik45kut.bkt.clouddn.com/WX20180821-233938.png)
![](http://owik45kut.bkt.clouddn.com/WX20180821-234002.png)

**Comment by 546669204** [comment]
apk 对不同环境有点问题 明天修复一下

**Comment by wenbobao** [comment]
好的，谢谢，辛苦了，早些休息，晚安！

**Comment by cdredfox** [comment]
访问  http://ip:1778 出现 404 page not found 请问一下，这个是什么原因

**Comment by 546669204** [comment]
@cdredfox  应该是msgprocess 服务没有起起来。 检查一下数据库没有配置或者缺少版本初始化文件msgprocess目录下需要有sql目录并且有sql文件

**Comment by 546669204** [comment]
@wenbobao  更新了app和wehoot 可以试试这个版本  https://github.com/546669204/wechatbot-xposed/releases/tag/1.0.0
