### ISSUE TITLE
能不能出一个详细一点的教程，拜托

### ISSUE THREAD

**Issue by Christopher-Songs** [546669204/RebateBot#2]
有一定的linux基础，但对go语言和MySQL完全不了解，现在使用go get直接卡在了`go get: no install location for directory /home/christ/bin/RebateBot outside GOPATH
	For more details see: 'go help gopath'`，这个问题肯定很初级，但对新手来说还是一道坎。如果可以，麻烦出一个hand by hand的教程，谢谢

**Comment by Christopher-Songs** [comment]
另外，如果只是想运行的话，是不是只需要执行
Download latest version of server and latest version of WeChat robot
Open the primary server
Install WeChatBot in mobile phones
Visit http://IP:1778 for alimama login
Test communication
不需要管后面的development and build？？

**Comment by 546669204** [comment]
把release包下载下来 然后到github上下载msgprocess目录下的sql文件夹放到 本地同目录下。并且配置好数据库。启用服务器。然后安装app并且启用。

**Comment by jpfree** [comment]
和层主一样的问题。也想求一个自己编译运行的方法。

**Comment by 546669204** [comment]
如果要自己 编译的话 
- 首先安装go环境
- clone 项目
- 进入各个文件夹 安装依赖 (go get)
- 配置mysql
- `go run master.go`

**Comment by Christopher-Songs** [comment]
实在是不好意思，对数据库完全不懂，安装了MySQL之后是不是还需要create database webot？能不能给一个详细的操作流程？我现在直接用的release版，sql文件夹也替换了，出现如下错误
`[root@server RedbateBot]# ./RebateBot 
2018-08-28 09:48:13   Over Time Close: 
Disconnected :23.226.136.202:50249
2018-08-28 09:48:13   connection error:  read tcp 155.94.140.234:188->23.226.136.202:50249: use of closed network connection
2018-08-28 09:48:44   Over Time Close: 
Disconnected :23.226.136.202:40517
2018-08-28 09:48:44   connection error:  read tcp 155.94.140.234:188->23.226.136.202:40517: use of closed network connection
`

**Comment by Christopher-Songs** [comment]
实在是不好意思，对数据库完全不懂，安装了MySQL之后是不是还需要create database webot？能不能给一个详细的操作流程？我现在直接用的release版，sql文件夹也替换了，出现如下错误
`[root@server RedbateBot]# ./RebateBot`
`2018-08-28 09:48:13 Over Time Close: Disconnected :xxxx:50249 2018-08-28 09:48:13 connection error: read tcp xxxx:188->xxxx:50249: use of closed network connection 2018-08-28 09:48:44 Over Time Close: Disconnected :xxxx:40517 2018-08-28 09:48:44 connection error: read tcp xxxx:188->xxxx:40517: use of closed network connection`

**Comment by jpfree** [comment]
安装了MYSQL后，需要创建一个数据库，再把数据库导入进去。建议新手用PHPMYADMIN这样的管理工具就很方便了。数据库名称和密码之类要和配置文件里对应。我也用的RELEASE版，已经跑起来了，但功能有点弱，查询商品都不行，可能有内置的机器人，自问自答还是很有意思的。。。。感谢作者的玩具。

在WIN下安装GO环境后，GO GET也是提示`现在使用go get直接卡在了go get: no install location for directory /home/christ/bin/RebateBot outside GOPATH For more details see: 'go help gopath'，环境变量应该没啥问题。`

**Comment by 546669204** [comment]
gopath的这个环境变量没有配置好，阿里妈妈登录了吗？需要登录才能查询商品

**Comment by jpfree** [comment]
WIN10，用系统属性或用命令GO ENV,里面有 set GOPATH=C:\Users\tom\go，有这个目录啊。

msgprocess这里一直提示未登录，但阿里妈妈是登陆上了的。查询商品意思是说 你输入指令 如 查找 云南白药 这样的，就自动返回 几条信息。

**Comment by 546669204** [comment]
msgprocess 没有登录没有关系的  目前需要发送链接或者 淘口令才能查询
