### ISSUE TITLE
screentshot和二维码登录问题

### ISSUE THREAD

**Issue by kelvindc** [546669204/RebateBot#4]
在ubuntu / osx遇到
screentshot 会有时移位（基本上都只capture左边广告）和扫瞄二维码登录不了，手机扫瞄显示二维码过期

**Comment by KimChow** [comment]
我在windows也遇到一样的问题，我基本上都是处于capture左边广告

**Comment by 546669204** [comment]
这个问题是必现吗，还是说 重开软件 之后的 第一次不会出现 第二第三次都是这样的

**Comment by kelvindc** [comment]
一開始3－4次是第一次不会出现 第二第三次都是这样的，
然後就無論如何重新來過都會出現

嗯，我试过改那个插件，
由截取dom el 改成直接把图片抄过来，
结果也是会二维码过期，会不会可能是客户端不能关掉，例如如果server弄个类似websocket的保持连线，一旦断就立刻令二维码过期

**Comment by 546669204** [comment]
是在本地环境下测试的吗。如果是异地登录的话可能会掉线。
每次生成二维码之前把所有的chrome浏览器都关掉。
