### ISSUE TITLE
linux64.zip 解压之后运行RebateBot 无反应

### ISSUE THREAD

**Issue by saxon17** [546669204/RebateBot#6]
2018/10/27 17:53:57 服务运行成功  {msgprocess 1} PID  <nil>
2018/10/27 17:53:57 服务运行成功  {alimama 1} PID  <nil>
2018/10/27 17:53:57 
2018/10/27 17:53:57 

已经靠背sql文件夹到制定目录下

是需要检查sql服务又没有启动码 请教

**Comment by 546669204** [comment]
可以查看 各目录下的log文件寻找问题。
现在可以看看是否有sql文件 并且里面有没有sql文件

**Comment by saxon17** [comment]
有sql 文件，但是看log 说 w**数据库不存在

**Comment by saxon17** [comment]
原来需要先建一个webot数据库

**Comment by 546669204** [comment]
是的
