### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by shao-hua-li** [546669204/RebateBot#7]
我成功的跑起来服务了👏👏👏，然而，扫码后并不能成功登录alimama，我看alimama的log显示“登录失败”，是不是现在已经不能用那个二维码扫描了？或者说链接需要更新了？因为用淘宝客户端扫描显示来源不明的二维码。

**Comment by 546669204** [comment]
在liunx上吗 不要异地登录  不要异地登录  不要异地登录 异地登录有不知名错误
如果在liunx上可以先清除所有chrome进程再尝试点击登录

**Comment by shao-hua-li** [comment]
没有异地登录。清除chrome也没用。我是在ubuntu16.04上搞的，windows的一直有问题。个人感觉可能是改版的问题，导致现在无法登录。或者我自己的问题，但是我正常从网页端扫码登录阿里妈妈是可以的。你能登录@546669204 ？

**Comment by 546669204** [comment]
@shao-hua-li  这个我好久没有用了但是一个星期之前还是有成功登陆的。

**Comment by shao-hua-li** [comment]
我发现问题了，问题是扫描二维码之后chromedp的后台并没有跳转到pub.alimama.com，而是停留在登录的那个页面，所有chromedp.Location得到的不是pub.alimama.com，判断登录失败。我在想是不是chromedp在这里有bug，就是并不能执行某些页面的函数，导致无法跳转。

**Comment by 546669204** [comment]
按理说是没有问题的 chrome 就是一个浏览器 执行页面的脚本没问题。 可能是阿里监测系统版本啥的 限制了
